In [5]:
import numpy as np

# Step 1: Create a random vector of size 15 with integers from 1 to 20
arr = np.random.randint(1, 21, size=15)
print("Original Vector:\n", arr)

# Step 2: Reshape the array to 3 rows and 5 columns
arr = arr.reshape(3, 5)
print("\nReshaped Array (3x5):\n", arr)

# Step 3: Print the shape of the array
print("\nArray Shape:", arr.shape)

# Step 4: Replace the max in each row with 0 (vectorized method)
row_indices = np.arange(arr.shape[0])
max_indices = arr.argmax(axis=1)
arr[row_indices, max_indices] = 0

# Step 5: Print final result
print("\nFinal Array (max in each row replaced with 0):\n", arr)


Original Vector:
 [ 2  5 12  3  8 16  4 15 11 20 19 19 12  9  4]

Reshaped Array (3x5):
 [[ 2  5 12  3  8]
 [16  4 15 11 20]
 [19 19 12  9  4]]

Array Shape: (3, 5)

Final Array (max in each row replaced with 0):
 [[ 2  5  0  3  8]
 [16  4 15 11  0]
 [ 0 19 12  9  4]]


In [ ]:
import numpy as np

# Step 1: Create a 2D array of size 4x3 with 4-byte integer elements (int32)
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9],
                [10, 11, 12]], dtype=np.int32)

# Step 2: Print the array
print("Array:\n", arr)

# Step 3: Print the shape of the array
print("\nShape:", arr.shape)

# Step 4: Print the type of the array
print("Type:", type(arr))

# Step 5: Print the data type of the elements
print("Data type of elements:", arr.dtype)


Array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Shape: (4, 3)
Type: <class 'numpy.ndarray'>
Data type of elements: int32


In [ ]:
import numpy as np

# Step 1: Define the square matrix
matrix = np.array([[3, -2],
                   [1,  0]])

# Step 2: Compute eigenvalues and right eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

# Step 3: Print the results
print("Matrix:\n", matrix)
print("\nEigenvalues:\n", eigenvalues)
print("\nRight Eigenvectors (each column is an eigenvector):\n", eigenvectors)


Matrix:
 [[ 3 -2]
 [ 1  0]]

Eigenvalues:
 [2. 1.]

Right Eigenvectors (each column is an eigenvector):
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [ ]:
import numpy as np

# Step 1: Define the array
arr = np.array([[0, 1, 2],
                [3, 4, 5]])

# Step 2: Compute the diagonal
diagonal_elements = np.diag(arr)

# Step 3: Compute the sum
sum_diagonal = np.sum(diagonal_elements)

# Print results
print("Array:\n", arr)
print("\nDiagonal Elements:", diagonal_elements)
print("Sum of Diagonal Elements:", sum_diagonal)


Array:
 [[0 1 2]
 [3 4 5]]

Diagonal Elements: [0 4]
Sum of Diagonal Elements: 4


In [ ]:
import numpy as np

# Original array 3x2
arr = np.array([[1, 2],
                [3, 4],
                [5, 6]])
print("Original array (3x2):")
print(arr)

# Reshape to 2x3
reshaped_arr = arr.reshape(2, 3)
print("\nReshaped array (2x3):")
print(reshaped_arr)


Original array (3x2):
[[1 2]
 [3 4]
 [5 6]]

Reshaped array (2x3):
[[1 2 3]
 [4 5 6]]
